#!/usr/bin/env python
import os, shutil, getpass

def remove_any(path):
    if os.path.islink(path): os.unlink(path)
    if os.path.isfile(path): os.remove(path)
    if os.path.isdir(path): shutil.rmtree(path)

def make_path(*args):
    return '/'.join(args)

scriptpath = os.path.dirname(os.path.realpath(__file__))
dirname = make_path(scriptpath, 'emacs.d')

homedir  = os.path.expanduser("~")
dot_emacs_dir = make_path(homedir, '.emacs.d')

remove_any(dot_emacs_dir)
os.mkdir(dot_emacs_dir)

for name in os.listdir(dirname):
    head = make_path(dirname, name)
    tail = make_path(dot_emacs_dir, name)
    remove_any(tail)
    os.symlink(head, tail)
