#!/usr/bin/env python
from distutils.spawn import find_executable
import os.path
import os

def make_content(template_path, emacs_client_path):
    with open(template_path, "r") as myfile:
        return myfile.read().format(emacs_client_path)

def create_file(content, path):
    command = "echo \"{0}\" > {1}".format(content, path)
    os.system(command)

def get_executable(executable_name):
    executable = find_executable("emacsclient")
    if executable:
        return os.path.abspath(executable)
    else:
        raise "could not find emacsclient executable."

executable_path = get_executable("emacsclient")
template_path = "emacs.template.desktop"
content = make_content(template_path, executable_path)

shortcut_path = "/usr/share/applications/emacs24.desktop"

create_file(content, shortcut_path)
