#!/usr/bin/env bash
set -euo pipefail

__DIR__=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
__GIT_ROOT__=$(git rev-parse --show-toplevel)
EMACS_DIR="${HOME}/.emacs.d"

ln -sf "${__GIT_ROOT__}/lisp" "${EMACS_DIR}"

echo -e "\e[0;32mDone!\e[0m"
